[tool.poetry]
name = "instagramunfollowers"
version = "0.1.0"
description = ""
authors = ["isakpulkki"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
instaloader = "^4.9.6"
invoke = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
